canbus: vcan0
kcd: gm_global_a_hs.kcd
font: test.tff
displays:
  all:
  - abs_active
  - accelerator_actual_position
  #- accelerator_pedal_validity
  - advance_fuel_flow_estimate
  #- bar_pressure_absolute_validity
  - barametric_absolute_pressure
  - boost_pressure_indication
  #- brake_pedal_driver_applied_pressure_detected
  #- brake_pedal_driver_applied_pressure_valid
  - brake_temperature_estimated
  - chassis_braking_load
  - commanded_air_fuel_ratio
  #- cruise_control_active
  #- cruise_control_enabled
  #- cruise_control_selected_speed
  #- distance_rolling_count_average_driven
  #- distance_rolling_count_average_driven_source
  #- distance_rolling_count_average_non_driven
  #- distance_rolling_count_average_non_driven_reset
  #- distance_rolling_count_average_non_driven_valid
  #- distance_rolling_count_average_reset_occured
  #- distance_rolling_count_average_valid
  #- driver_throttle_override_detected
  #- engine_coolant_temp_validity
  - engine_coolant_temperature
  - engine_idle_active
  - engine_intake_temperature
  - engine_oil_pressure
  - engine_oil_temp
  - engine_run_active
  - engine_speed
  #- engine_speed_status
  - engine_warmup_cycle_achieved
  #- exhaust_pressue_regulator_valve_position
  #- exhaust_pressue_regulator_valve_validity
  - fuel_consumption_rate
  - fuel_delivery_pressure_requested
  - fuel_pressure_esimated_pressure_delivered
  - fuel_level_percent
  #- fuel_pump_enabled_descrete_output_status
  #- fuel_system_estimated_pressue_valid
  #- fuel_system_fault_present
  - gear_shift_direction
  - inst_fuel_flow_estimate
  #- intake_temp_validity
  #- legislated_diagnostics_conditions_fault_present
  #- legislated_diagnostics_conditions_met
  #- moderate_brake_achieved
  #- outside_air_estimate_temp_mask
  #- outside_air_estimate_temp_validity
  - outside_air_temperature_estimate
  - platform_brake_position
  #- powertrain_brake_pedal_descrete_input_status
  #- powertrain_brake_pedal_descrete_input_valid
  #- powertrain_crank_aborted
  #- powertrain_crank_active
  #- powertrain_run_aborted
  - requested_gear
  #- skip_shift_active
  - speed_average_driven_valid
  #- speed_average_driven_validity
  #- speed_average_non_driven_valid
  - steering_wheel_angle
  - tcs_active
  - throttle_position
  #- top_clutch_travel
  - total_fuel_capacity
  #- trans_emissions_related_malfunction
  #- trans_non_emissions_related_malfunction
  #- trans_oil_change_now_indicator
  - trans_oil_temp
  #- trans_oil_temp_present
  #- trans_oil_temp_valid
  - trans_thermal_management_status
  - transmission_commanded_gear
  - transmission_estimated_gear
  - transmission_torque_converter_clutch_mode
  - vdcs_active
  - vdcs_understeer_active
  #- vdcs_understeer_valid
  #- vdcs_yaw_rate_valid
  - vehicle_average_speed_soruce
  - vehicle_dynamics_yaw_rate
  #- vehicle_speed_average_non_driven_validity
  - vehicle_stability_lateral_acceleration
  #- vehicle_stability_lateral_acceleration_valid
  dynamics:
  - abs_active
  - accelerator_actual_position
  - throttle_position
  - brake_temperature_estimated
  - chassis_braking_load
  - platform_brake_position
  - vdcs_active
  - vdcs_understeer_active
  - vehicle_average_speed_soruce
  - vehicle_dynamics_yaw_rate
  - vehicle_stability_lateral_acceleration
  - steering_wheel_angle
  - tcs_active
  engine:
  - accelerator_actual_position
  - throttle_position
  - boost_pressure_indication
  - advance_fuel_flow_estimate
  - commanded_air_fuel_ratio
  - engine_coolant_temperature
  - engine_idle_active
  - engine_intake_temperature
  - engine_oil_pressure
  - engine_oil_temp
  - engine_run_active
  - engine_speed
  - engine_warmup_cycle_achieved
  - inst_fuel_flow_estimate
  - fuel_consumption_rate
  - fuel_delivery_pressure_requested
  - fuel_pressure_esimated_pressure_delivered
  transmission:
  - gear_shift_direction
  - requested_gear
  - trans_oil_temp
  - trans_thermal_management_status
  - transmission_commanded_gear
  - transmission_estimated_gear
  - transmission_torque_converter_clutch_mode
